### ISSUE TITLE
ReHitman is not working on my game

### ISSUE THREAD

**Issue by garstas** [ReGlacier/ReHitman#6]
I'm trying to run the project on my local Hitman installation (build is compatible), but I always get errors when I try to run `Launch.ReHitman.exe` while the game process is running. When the game is not started yet, I see some green checks in ReHitman console (I can run the game after, but I can't open the debug menu (F3, right?) and it seems like nothing is attached to the game process).

When the game is not launched:
![image](https://user-images.githubusercontent.com/19244786/116834656-c19c0000-abc7-11eb-8889-8a701ad3b9e7.png)

When the game process is running I randomly get either of these:
![image](https://user-images.githubusercontent.com/19244786/116834741-235c6a00-abc8-11eb-8ce8-82cafce5236d.png)

![image](https://user-images.githubusercontent.com/19244786/116834862-ab427400-abc8-11eb-88d1-adf5a771f5cb.png)

I tried different releases (even tried the last one from the appveyor)

**Comment by DronCode** [comment]
Sorry for the delay. Hmm, looks interesting. Could you provide a game version? Looks like the game version detected correctly, but it's unable to apply the required patches, and after that game crashing. Oh and maybe you have antimalware software (it could block work of in-memory work but it shouldn't. Anyway, could you provide its name if it's used).

**Comment by garstas** [comment]
Hitman Version: 1.2  (https://www.gog.com/game/hitman_blood_money, installed it via their so-called "GOG Galaxy" client, but I run it using hitman's raw exe, by the way), in HitmanBloodMoney.exe's HEX: `�secs����english�blood-build3-20060616-26123�`
Windows 10 build: 20H2 (19042.928)

I also use my Steam version savefiles profile, but I don't think it could affect the addresses and other stuff.

> Oh and maybe you have antimalware software

I use Avast Free antivirus, but I disable it when I try to run ReHitman, it detects the launcher exe as malware :)

I also found this patch in GOG Galaxy launcher tab (maybe it's important I dunno), anyway I can't find any unpatched versions (on torrents too) so i guess you also use the patched one:
![image](https://user-images.githubusercontent.com/19244786/117183880-c1c31800-ade0-11eb-9ffc-7fc5482d17b9.png)

**Comment by DronCode** [comment]
Hmm, I'm using 1.2 patch but as I know in GoG uploaded an updated version and their patch could conflict with us. 
Anyway, I will check it, thank you for your report :)

**Comment by garstas** [comment]
GOG has another direct offline method and it seems like you can omit the fixing patch, will check this unpatched version later and let you know.
![image](https://user-images.githubusercontent.com/19244786/117186841-ea98dc80-ade3-11eb-82c7-f07e20c9aba1.png)

**Comment by garstas** [comment]
Nope, didn't work, the same issues 😢 

By the way, i installed that patch and the game exe is now 7 216KB (but it was 4 264KB like the GOG Galaxy one, lol). So, i guess galaxy launcher has no 1.2 hotfixes, because when i applied the patch above - im now getting this:
![image](https://user-images.githubusercontent.com/19244786/117189571-08b40c00-ade7-11eb-8b13-6b7c5503d98f.png)

**Comment by DronCode** [comment]
All right, I will try to reproduce that on the latest GoG build. 
Maybe some offsets are changed or smth like that.

**Comment by DronCode** [comment]
@godstanis, I tried to reproduce that behaviour on the latest GoG version (downloaded from GoG Galaxy today) but it's doesn' t reproduced for me on clean Win10 in VM. Could you contact me via Discord?

**Comment by DronCode** [comment]
Found solution. Need to update documentation about launch process. At the "Launcher.ReHitman.exe" console window user should press any key to launch the game. Otherwise, the game will not be launched correctly.

**Comment by HHCHunter** [comment]
@DronCode @godstanis 
Updated / wrote stub document
https://github.com/ReGlacier/ReHitman/wiki/How-to-Run-ReHitman

**Comment by HHCHunter** [comment]
We can probably close this issue off right?

**Comment by garstas** [comment]
Yeah, sure
